ktor:
  application:
    modules:
      - com.rarnu.mdpro3.MainKt.module
    version: 1.0.0.0
  deployment:
    port: 38383
    sslPort: 38443
  security:
    ssl:
      keyStore: "/etc/letsencrypt/live/zgai.tech/keystore.jks"
      keyAlias: "zgai"
      keyStorePassword: "Rarnu1120"
      privateKeyPassword: "Rarnu1120"
#      keyStore: "/etc/letsencrypt/live/rarnu.xyz/keystore.jks"
#      keyAlias: "rarnu"
#      keyStorePassword: "Rarnu1120"
#      privateKeyPassword: "Rarnu1120"

database:
  mdpro3:
    jdbcUrl: "jdbc:mysql://localhost:3306/mdpro3?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai"
    user: root
    password: rootroot
  nameapi:
    jdbcUrl: "jdbc:mysql://localhost:3306/YugiohAPI2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai"
    user: root
    password: rootroot
  omega:
    jdbcUrl: "jdbc:sqlite:files/OmegaDB.cdb"