ktor:
  application:
    modules:
      - com.rarnu.mdpro3.MainKt.module
    version: 1.0.0.0
  deployment:
    port: 38383

database:
  jdbcUrl: "jdbc:mysql://localhost:3306/mdpro3?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai"
  user: root
  password: rootroot
