package com.rarnu.mdpro3.define

val HTTP_ERR_SERVER = 500 to ""
val HTTP_ERR_BAD_REQUEST = 400 to "客户端请求接口 [%s] 时，请求内容错误"
val HTTP_ERR_NOT_FOUND = 404 to "请求的路由 [%s] 不存在"
val HTTP_ERR_METHOD_NOT_ALLOWED = 405 to "路由 [%s] 不支持 [%s] 请求方式"
val HTTP_ERR_REQUEST_TIMEOUT = 408 to "请求路由 [%s] 超时"
val HTTP_ERR_RATE_LIMIT_EXCEEDED = 429 to "接口 [%s] 不能在当前被请求，已超过限流设置"

val ERR_UPLOAD_DECK = 1 to "上传卡组错误"
val ERR_NO_CONTRIBUTOR = 2 to "没有传入贡献者"
val ERR_NO_DECK_ID = 3 to "没有传入卡组 ID"
val ERR_NO_DECK_NAME = 4 to "没有传入卡组名称"
val ERR_NO_YDK = 5 to "没有传入 YDK 内容"
val ERR_YDK_NOT_VALID = 6 to "YDK 内容不合法，主卡组必须满 40 张"
val ERR_UPDATE_DECK = 7 to "更新卡组错误"
val ERR_DELETE_DECK = 8 to "删除卡组错误"
val ERR_DECK_NOT_EXISTS = 9 to "卡组不存在"
val ERR_LIKE_TOO_NEAR = 10 to "点赞过于频繁，请于 10 分钟后再试"
val ERR_REQ_SOURCE = 11 to "请求来源不正确"
val ERR_NO_WORD = 12 to "没有提供文本"
val ERR_NAME_IS_SENSITIVE = 13 to "卡组或贡献者名称中包含敏感词「[?]」，不能上传"
val ERR_NO_TOKEN = 14 to "没有传入 token"
val ERR_NO_USER_ID = 15 to "没有传入用户 ID"
val ERR_SYNC_FAIL = 16 to "同步卡组失败"
val ERR_DAU_SRC = 17 to "未提供 DAU 分析的来源"
val ERR_DAU_YEAR = 18 to "未提供 DAU 分析的年份"
val ERR_DAU_MONTH = 19 to "未提供 DAU 分析的月份"
val ERR_USER_VALIDATE = 20 to "验证用户身份失败"
val ERR_NOT_ADMIN = 21 to "您没有管理员权限"
val ERR_NO_PUZZLE_ID = 22 to "没有传入残局 ID"
val ERR_PUZZLE_NOT_EXISTS = 23 to "残局不存在"
val ERR_PUZZLE_OWNER = 24 to "您无权编辑这个残局"