package com.rarnu.mdpro3.define

val ERR_UPLOAD_DECK = 1 to "上传卡组错误"
val ERR_NO_CONTRIBUTOR = 2 to "没有传入贡献者"
val ERR_NO_DECK_ID = 3 to "没有传入卡组 ID"
val ERR_NO_DECK_NAME = 4 to "没有传入卡组名称"
val ERR_NO_YDK = 5 to "没有传入 YDK 内容"
val ERR_YDK_NOT_VALID = 6 to "YDK 内容不合法，主卡组必须满 40 张"
val ERR_UPDATE_DECK = 7 to "更新卡组错误"
val ERR_DELETE_DECK = 8 to "删除卡组错误"
val ERR_DECK_NOT_EXISTS = 9 to "卡组不存在"
val ERR_LIKE_TOO_NEAR = 10 to "点赞过于频繁，请于 10 分钟后再试"
val ERR_REQ_SOURCE = 11 to "请求来源不正确"
val ERR_NO_WORD = 12 to "没有提供文本"
val ERR_NAME_IS_SENSITIVE = 13 to "卡组或贡献者名称中包含敏感词[%s]，不能上传"
